# NetTwin-SOC Alembic 配置文件

[alembic]
# 迁移脚本路径
script_location = alembic

# 生成迁移文件的模板
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s

# sys.path 前置路径
prepend_sys_path = .

# 文件模板日期时区
# timezone = UTC

# 版本名称最大长度
# truncate_slug_length = 40

# 版本命名规则
# revision_environment = false

# 无源文件模式
# sourceless = false

# 版本路径分隔符
# version_path_separator = os

# version_locations 定义搜索迁移文件的额外目录
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# 输出编码
# output_encoding = utf-8

sqlalchemy.url = sqlite:///./data/nettwin.db


[post_write_hooks]
# post_write_hooks 定义在新版本脚本生成后执行的脚本或 Python 函数

# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -q


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
